Enable Golang web server, Golang gRPC, and Golang SQLite tests for CI
occlum/occlum pull request #170
Opened 2020-09-29 08:26 UTC by james-dong-security

Enable Golang web server, Golang gRPC, and Golang SQLite tests for CI

2020-09-29 11:09 UTC, jessehui requested changes
Thank you for submitting this. Looks good in general.  Add some comments about the format.

2020-09-29 16:09 UTC, james-dong-security commented on .github/workflows/demo_test.yml
> +  Golang_WebServer_test:
Thanks for pointing this out. Removed the duplicate runs.

2020-09-29 16:10 UTC, james-dong-security commented on .github/workflows/demo_test.yml
> +  Golang_SQLite_test:
Done

2020-09-29 16:10 UTC, james-dong-security commented on .github/workflows/demo_test.yml
> +  Golang_gRPC_test:
Thanks for pointing this out. Removed the duplicate runs.

2020-09-29 16:43 UTC, james-dong-security commented
@jessehui : 
Thanks for reviewing earlier patch, and for catching the duplicate tests. Made changes accordingly. PTAL.

2020-09-30 02:52 UTC, jessehui approved these changes
LGTM

2020-10-15 02:06 UTC, jessehui approved these changes

2020-10-15 02:06 UTC, tatetian approved these changes
LGTM

2020-10-15 02:07 UTC, merged