BUG: incompatible timespec convertion from rust to c
occlum/occlum pull request #776
Opened 2022-01-11 08:53 UTC by amazingAmy

Cannot get correct time when running java/c program in occlum due to incompatible timespec convertion from Rust to C. Actually, the ability of getting correct time is very important for some applications, for example, using JAVA FileLock which repetitively check file last-change time. This bug would make those application rush to error.
The bug is caused by incompatible timespec conversion in Rust ({i64, i32}) and C ({long, long}). When C program invokes a Rust lib to get one variable (e.g., info) including  timespec-type value (info.atime), the result in C  is not same to that generated in Rust.
Remember to check [#40](https://github.com/occlum/sefs/pull/40#issue-1098863814) which also includes one sample code.
In additional, thanks to @liqinggd for his generous help.

2022-01-11 09:12 UTC, liqinggd requested changes
Thanks for the contribution, Please change the git config with a valid user name and email address.

BTW, there are many codes that use `Timespec`, you should change them all.

2022-01-11 10:37 UTC, guzongmin commented
@amazingAmy Thanks for your PR. The CI for this PR failed, I think it may be caused by the SEFS submodule which is not updated at the meantime.

2022-01-12 05:25 UTC, liqinggd commented
Please squash the 2 commits together.

2022-01-12 05:49 UTC, guzongmin reviewed
The Enclave_private.pem update should not be part of the fix. Please remove the modification.

2022-01-12 10:08 UTC, liqinggd commented
LGTM

2022-01-12 10:41 UTC, guzongmin approved these changes
LGTM

2022-01-12 10:42 UTC, merged